FROM <BASE_IMAGE/>

COPY plugins /var/lib/grafana/plugins
COPY grafana.ini /etc/grafana/grafana.ini

ENV GF_AWS_PROFILES=default
ENV GF_AWS_default_ACCESS_KEY_ID=<AWS_ACCESS_KEY/>
ENV GF_AWS_default_SECRET_ACCESS_KEY=<AWS_SECRET_KEY/>
ENV GF_AWS_default_REGION=<AWS_REGION/>
