name: get-secrets

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: export secrets
      shell: bash
      env:
        MAXION_CLIENT_ID: ${{ secrets.MAXION_CLIENT_ID }}
        MAXION_CLIENT_SECRET: ${{ secrets.MAXION_CLIENT_SECRET }}
        OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
      run: |
        set -x
        echo "MAXION_CLIENT_ID=${MAXION_CLIENT_ID}" > "secrets"
        echo "MAXION_CLIENT_SECRET=${MAXION_CLIENT_SECRET}" >> "secrets"
        echo "OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}" >> "secrets"
        echo "OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}" >> "secrets"
        echo "SMTP_HOST=${SMTP_HOST}" >> "secrets"
        echo "SMTP_PASSWORD=${SMTP_PASSWORD}" >> "secrets"
        echo "SMTP_USER=${SMTP_USER}" >> "secrets"
    - name: upload secrets
      uses: actions/upload-artifact@v4
      with:
        name: secrets
        path: secrets
        if-no-files-found: error
        retention-days: 1
        overwrite: true
