name: PR Automation

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review      
      - labeled
      - unlabeled
  issues:
    types:
      - milestoned
      - demilestoned

jobs:
  checks:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run PR Checks
        uses: ./actions/pr-checks
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: pr-checks

  commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: pr-commands

  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ github.event.number }}
        message: 'Please deploy and test the PR on development environment before merging. To do this add pr/deploy label to the PR.'
