name: Run tests on main

on:
  push:
    branches: [main]

jobs:
  test-go:
    runs-on: ubuntu-latest
    container: golang:1.17.6-alpine3.15
    steps:
    - uses: actions/checkout@v2
    - run: |
        apk add --no-cache gcc g++ make
        make gen-go
        make lint-go
        make test-go

  test-js:
    runs-on: ubuntu-latest
    container: node:16-alpine3.15
    steps:
    - uses: actions/checkout@v2
    - run: |
        yarn install --immutable
        yarn test --no-watch
