name: Deploy Dashboards

on:
  workflow_dispatch:

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run Deployment script
        run: |
          python .github/tvarit/dashboard-deployment.py
