name: Update changelog
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone
  workflow_call:
    inputs:
      version_call:
        description: Needs to match, exactly, the name of a milestone
        required: true
        type: string
    secrets:
        token:
          required: true
        metricsWriteAPIKey:
          required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run update changelog (manually invoked)
        if: ${{ github.event.inputs.version != '' }}
        uses: ./actions/update-changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run update changelog (workflow invoked)
        if: ${{ inputs.version_call != '' }}
        uses: ./actions/update-changelog
        with:
          version_call: ${{ inputs.version_call }}
          token: ${{ secrets.token }}
